# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5904feba2c020627b89e961b4d98c5c81c856ce2199603761fc26a7151df07979fe426d13f45568f80c4ce08f932623e8343654c09b41b039419c86c32966d4

test:
  secret_key_base: 7f4ac7688e5c1de3f9d0704ba8012880d228a43eae3917d7310878e819f5bd3d1e3180fa48088d81270fbcc59e5e0d306f59710ea6ea3de17c02d7c87bce1bea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
